python dataPreprocess/json_to_csv_converter.py data/yelp_dataset_challenge_round9/yelp_academic_dataset_checkin.json
python dataPreprocess/json_to_csv_converter.py data/yelp_dataset_challenge_round9/yelp_academic_dataset_business.json
python dataPreprocess/json_to_csv_converter.py data/yelp_dataset_challenge_round9/yelp_academic_dataset_tip.json
python dataPreprocess/json_to_csv_converter.py data/yelp_dataset_challenge_round9/yelp_academic_dataset_review.json
python dataPreprocess/json_to_csv_converter.py data/yelp_dataset_challenge_round9/yelp_academic_dataset_user.json
